# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ASPNETCORE_ENVIRONMENT: '$(ASPNETCORE_ENVIRONMENT)'
  BRANCH_NAME: '$(BRANCH_NAME)'
  MYSQL_CONNECTION_STRING: '$(MYSQL_CONNECTION_STRING)'
  REPO_NAME: '$(REPO_NAME)'
  SQLSERVER_CONNECTION_STRING: '$(SQLSERVER_CONNECTION_STRING)'

steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'

- task: NuGetCommand@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    verbosityRestore: 'Normal'

- task: DotNetCoreCLI@1
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'UmaMusumeLoadSqlData/UmamusumeLoadSqlData.csproj'

- task: PowerShell@2
  displayName: 'Set environment variables'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Making the sauceUsername available as an environment variable."
      Write-Host "##vso[task.setvariable variable=ASPNETCORE_ENVIRONMENT;]$(ASPNETCORE_ENVIRONMENT)"

- task: DotNetCoreCLI@2
  displayName: 'Run'
  inputs:
    command: 'run'
    projects: 'UmaMusumeLoadSqlData/UmamusumeLoadSqlData.csproj'

